### PR TITLE
Rate endpoint

### PR DESCRIPTION
**Pull request by alexeyzab**
Hey Chris!

I've started working on another endpoint now. This one just uses a GET method and some query params. I am not quite sure how to implement those yet.

Should it be an additional optional parameter for `ShipWireRequest`?

Like so:

```
data ShipWireRequest a = ShipWireRequest
  { rMethod  :: Method -- ^ Method of ShipWireRequest
  , endpoint :: Text -- ^ Endpoint of ShipWireRequest
  , body     :: Maybe BSL.ByteString -- ^ Request body of ShipWireRequest
  , params   :: Maybe Params -- ^ Params of ShipWireRequest
  }

type Params = [(ByteString, ByteString])

mkShipWireRequest :: Method -> Text -> Maybe BSL.ByteString -> Maybe Params -> ShipWireRequest a
mkShipWireRequest m e b p = ShipWireRequest m e b p
```

I also need to add tests for this endpoint, can't seem to get ShipWire to let me send the virtual packages to their virtual warehouses for whatever reason. Will look into that.

### CODE REVIEW

**Comment by bitemyapp** [comment]
I think an empty list suffices for "maybe we have it, maybe we don't" unless you have a specific case in mind you want to guard for, otherwise it (+1)'s the cardinality for dubious benefit.

**Comment by alexeyzab** [comment]
@bitemyapp So we can add it directly to the Client's function that creates the request then?
i.e.:

```
createStockRequest :: Params -> ShipWireRequest StockRequest
createStockRequest p = request
  where
    request = mkShipWireRequest NHTM.methodGet url Nothing
    url = T.append $ (T.append sandboxUrl "/stock") appendParams p
```

**Comment by bitemyapp** [comment]
I think you'd want to centralize any URL construction or params serialization, not spread them across functions that create requests for different endpoints. Beyond that, not sure what you're asking, apologies.

**Comment by alexeyzab** [comment]
Makes sense, will work on that. Thank you! I think I am confused about how to allow the user to pass in the query parameters for a particular endpoint without increasing the cardinality of `ShipWireRequest` and spreading it across the functions like you've said. I'll figure it out.

**Comment by alexeyzab** [comment]
@bitemyapp Hey Chris! I've made some changes to how URLs are constructed, let me know if I should reassess  my approach.

Also, I was thinking about testing this and wanted to know your opinion on something:

in Stripe API for haskell it seems to be a common pattern to assume  

```
result `shouldSatisfy` isRight
```

at the end of each spec. Is this something we should be doing here as well? Constructing the appropriate response by hand seems to be error-prone. (The way I did it [here](https://github.com/bitemyapp/ballast/blob/master/tests/tests.hs#L62)) The exact response will depend on what the settings are like in the given Shipwire account.

**Comment by bitemyapp** [comment]
@alexeyzab I do think successful API responses should be `Right`, errors should be `Left`. The library should handle distinguishing those cases.

> Constructing the appropriate response by hand seems to be error-prone.

I'd take cues from Bloodhound and stripe-haskell/stripe-core here and not force the consumer of the API to assemble any HTTP requests manually. Instead, make a higher level API and abstract/generalize the noise away so there's less tedium and surface area for mistakes.

This is a bit harder for a newer person to just "come up with" an appropriate API ex nihilo so once you've got at least two API requests to generalize, ping me and we can pair program on it, if you're up for that.

**Comment by alexeyzab** [comment]
@bitemyapp I am torn between not increasing cardinality of  `ShipwireRequest a` and subsequently each endpoint function (i.e. `createRateRequest`) and not making the consumer of the API assemble the requests manually. Not sure how to do one without the other.

For example:

```
getCard
  :: URL
  -> ID
  -> Text -- card id
  -> StripeRequest a
getCard
  prefix
  id_
  cardid_      = request
  where request = mkStripeRequest GET url params
        url     = prefix </> id_ </>
                  "cards" </> cardid_
        params  = []
```

It seems that URL construction is happening here, is that something I should avoid with Ballast?

I am definitely up for that, if you have time. Should I start working on another endpoint that allows a GET request and query params then? So far we have `/rate` with POST and `/stock` with GET.

**Comment by bitemyapp** [comment]
`rate` and `stock are probably enough for now, but do as you think best gives us more material to work with in generalizing.

Hit me up in DMs about pairing.

**Comment by alexeyzab** [comment]
@bitemyapp Hey Chris! I've reworked the way this library works. It's now similar to the stripe haskell library. Let me know if the way I handle the optional query parameters and request body is alright. 

There is still more that needs to be done here, I need to write instances for other possible parameters for the endpoints and rewrite the tests. But I was wondering if I am on the right track here.

**Comment by alexeyzab** [comment]
I've added a couple of tests. Not yet sure if that's the way to go or not.

**Comment by bitemyapp** [comment]
@alexeyzab take a poke anon

**Comment by alexeyzab** [comment]
@bitemyapp Wait what, sorry I don't think I understand?

**Comment by bitemyapp** [comment]
screenshot from 2016-09-30 22-10-42

**Comment by alexeyzab** [comment]
@bitemyapp Ohhhh, that makes a lot more sense now.

**Comment by bitemyapp** [comment]
The ~in~ was _in_correct. Edited.

**Comment by alexeyzab** [comment]
At first I thought you started using imageboard slang all of a sudden.

**Comment by bitemyapp** [comment]
Dunno what's _s'posed_ to happen, but this is where I'm at with the tests.

screenshot from 2016-09-30 23-06-51

**Comment by bitemyapp** [comment]
I'm going to pop you a PR in a bit.

**Comment by alexeyzab** [comment]
Hmm, I wonder if it has to do with Shipwire account settings.

As in, setting up virtual deliveries so this endpoint would respond properly.

Will look into it.

**Comment by bitemyapp** [comment]
https://travis-ci.org/bitemyapp/ballast/builds coming along.

Having looked at the code, seems fine so far. Still going to need more surface area and examples of use to really suss out what'll need improved or not.

Tests passed just now. No idea what's going on.

**Comment by bitemyapp** [comment]
@alexeyzab http://www.folklore.org/StoryView.py?story=Make_a_Mess,_Clean_it_Up!.txt I found this helped me.

It's Haskell, we don't have to be afraid to make a mess as long as we avoid partiality and similar unforced errors.

**Comment by bitemyapp** [comment]
@alexeyzab https://github.com/alexeyzab/ballast/pull/1 there you go.

**Comment by alexeyzab** [comment]
@bitemyapp `sandboxEnvConfig` is set to production host here: https://github.com/alexeyzab/ballast/blob/rate-endpoint/src/Ballast/Types.hs#L825

Will fix it, just mentioning it in case it messes things up on CI or something.

**Comment by alexeyzab** [comment]
@bitemyapp If this seems fine so far, should I add the missing query params datatypes for this endpoint and move on to other endpoints?

**Comment by bitemyapp** [comment]
Tink so yeah!

**Comment by bitemyapp** [comment]
Moving to repo contribution instead of fork so that the tests work properly.

**Pull request merged**
