### PR TITLE
Finish /stock endpoint

### PR DESCRIPTION
**Pull request by alexeyzab**
@bitemyapp Hey Chris!

I went back to finishing the `/stock` endpoint for now. This has all the query parameters mentioned in the API documentation. Should I move on to other endpoints now?

### CODE REVIEW

**Comment by bitemyapp** [comment]
@alexeyzab amendment requested for #4, then I have a question for this:

Everything under `ShipwireHasParam` is an optional parameter right? The distinction between when the Stripe library used `HasParam` and plain function arguments was the former were for optional arguments only and the latter for obligatory arguments.

**Comment by alexeyzab** [comment]
@bitemyapp Yes, that's how I've been doing it here as well. `ShipwireHasParam` is for optional arguments which have all been query parameters so far.

**Comment by bitemyapp** [comment]
@alexeyzab merge master into this so it has the singular secure block.

Other than that, would there be a way to test this against the sandbox API? Fake the addition of some products to their warehouse, then check the Stock API for them?

**Comment by alexeyzab** [comment]
@bitemyapp I was thinking about that. Will work on it. How would those tests be reproduced locally, if they require a bunch of setup within a Shipwire account? Is that even a problem?

**Comment by bitemyapp** [comment]
@alexeyzab all code, no manual setup. The test provisions the test data required to run the test.

**Comment by alexeyzab** [comment]
@bitemyapp Ah, I see. Would need to set up the endpoint that sends stuff to the warehouse to check the stock afterwards. Or should it be a one-off JSON payload for now?

**Comment by bitemyapp** [comment]
I'd just implement it properly and make the test cover the functionality of both, but do what you think is best.

**Comment by alexeyzab** [comment]
I want to do that too, the only thing that bothers me is that I would need to go ahead and implement all the needed endpoints before coming back to testing this one. I hope that's okay.

**Comment by bitemyapp** [comment]
defo fine by me. You can merge this and you can start a new branch for that if you like.

**Comment by alexeyzab** [comment]
Sure, sounds good. Thanks Chris!

**Pull request merged**
