### PR TITLE
Receiving endpoint

### PR DESCRIPTION
**Pull request by alexeyzab**
Reopening this PR to finish this endpoint.

I was wondering if it would be okay to remove some tests to speed up the test suite. In particular, there are two tests for each endpoint where one has optional query params and one doesn't. Would it be okay to just add the params for each one? Less requests made that way.

### CODE REVIEW

**Comment by bitemyapp** [comment]
@alexeyzab that change sounds fine, go ahead and push it into this PR.

**Comment by alexeyzab** [comment]
@bitemyapp Great, will do. There are a few more things to do with this endpoint (namely, more functions like canceling a receiving and so on) I'll be working on that now.

**Comment by alexeyzab** [comment]
@bitemyapp I think that covers all of the `/receivings` endpoint functions. If it looks good, we can merge it in and I'll move on to `/products`.

**Comment by bitemyapp** [comment]
@alexeyzab :+1: :smile_cat:

**Pull request merged**
