### PR TITLE
Starting a new branch for fixing the random failures

### PR DESCRIPTION
**Pull request by alexeyzab**
This is just to see if I am submitting the PR correctly.

### CODE REVIEW

**Comment by bitemyapp** [comment]
Looks right. Has to be intra-repo or the security stuff elides the env so randos can't dump your creds.

Speaking of, don't print/dump the environment, I know that's obvious, but just saying.

**Comment by alexeyzab** [comment]
Alright, will make sure not to.

**Comment by alexeyzab** [comment]
Apparently this is what gets returned on CI:

```
"{\"status\":401,\"message\":\"Please include a valid Authorization header (Basic)\",\"resourceLocation\":null}"
```

I don't quite understand why this header would be set wrong for these two tests and right for the other one.

**Comment by alexeyzab** [comment]
@bitemyapp Hey Chris, looks like adding my own credentials to `.travis.yml` worked and CI build passes now. (Technically it still fails because I haven't removed the `debug` function, but the HTTP response is 200)

Should I keep my `.travis.yml` for future PRs? Is there anything that can be adjusted with the one you've made? I really don't know why it wasn't working. The only difference I am noticing is that I have two `secure` items listed instead of one. Added those with the `travis` gem. https://github.com/bitemyapp/ballast/pull/4/commits/80c1220e09f750ae4d7c6aaa84158ef098ddc7ea#diff-354f30a63fb0907d4ad57269548329e3R8

**Comment by bitemyapp** [comment]
@alexeyzab  Remove mine, keep yours, then I'll merge this and we'll continue like that.

**Comment by alexeyzab** [comment]
@bitemyapp Got it, the committed `.travis.yml` has only my credentials in it so it can be merged I think.

**Comment by bitemyapp** [comment]
@alexeyzab did you push? I see both: 
screenshot from 2016-10-05 10-52-11

**Comment by alexeyzab** [comment]
@bitemyapp Those are my email and password as two separate entries. Is this wrong?

**Comment by bitemyapp** [comment]
Oh I see now. I had combined both environment variables in a single secure var. `USER=blah PASS=blah` in a single line.

Could you add a single secure block with both env vars set in them please?

**Comment by alexeyzab** [comment]
Sure, will do.

**Pull request merged**
